# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: federated.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'federated.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66\x65\x64\x65rated.proto\x12\tfederated\"\x1c\n\x08Gradient\x12\x10\n\x08gradient\x18\x01 \x03(\x02\" \n\rGlobalWeights\x12\x0f\n\x07weights\x18\x01 \x03(\x02\x32R\n\x11\x46\x65\x64\x65ratedLearning\x12=\n\x0cSendGradient\x12\x13.federated.Gradient\x1a\x18.federated.GlobalWeightsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'federated_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GRADIENT']._serialized_start=30
  _globals['_GRADIENT']._serialized_end=58
  _globals['_GLOBALWEIGHTS']._serialized_start=60
  _globals['_GLOBALWEIGHTS']._serialized_end=92
  _globals['_FEDERATEDLEARNING']._serialized_start=94
  _globals['_FEDERATEDLEARNING']._serialized_end=176
# @@protoc_insertion_point(module_scope)
